### ISSUE TITLE
Exported symbols issue

### ISSUE THREAD

**Issue by mmontone** [antifuchs/cl-beanstalk#2]
There are two packages, `beanstalk` and `beanstalk-internal`. And although `beanstalk` exports several condition classes, they are undefined, as those conditions are defined in `beanstalk-internal`, not `beanstalk`.

In particular, that causes an error when signaling a `deadline-soon` warning, as it is referenced as `beanstalk:deadline-soon`, which is undefined.

**Comment by antifuchs** [comment]
Wow, this is unexpected: I haven't seen anyone use this library in several years (and haven't used in in almost as long...)

If you have a fix for this, I would be happy to merge a PR (and would even consider passing maintenance to you if you like). 

For the fix, I suspect the two package definitions need to trade places and the external package needs to import the condition symbols from the internal one?

**Comment by mmontone** [comment]
Yes. I think one solution could be to prefix condition names with `beanstalk` in the `define-condition` s. Like, `(define-condition beanstalk:deadline-soon .. ` . Then make sure to use the prefixed symbols when signaling the conditions ...

I'll have a look and make a pull a request if I manage to fix it.

**Comment by antifuchs** [comment]
That sounds great! My CL is a bit rusty (literally...) these days, so you're likely to be able to come up with a way more idiomatic solution than I (:
